import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * http://tools.android.com
     */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val legacy_preference_v14: String = "androidx.legacy:legacy-preference-v14:" +
            Versions.androidx_legacy

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val legacy_support_v4: String = "androidx.legacy:legacy-support-v4:" +
            Versions.androidx_legacy

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:" +
            Versions.lifecycle_extensions

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_fragment_ktx: String = "androidx.navigation:navigation-fragment-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:" + Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:" +
            Versions.androidx_navigation

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val preference: String = "androidx.preference:preference:" + Versions.preference

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val room_compiler: String = "androidx.room:room-compiler:" + Versions.androidx_room

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val room_runtime: String = "androidx.room:room-runtime:" + Versions.androidx_room

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val room_rxjava2: String = "androidx.room:room-rxjava2:" + Versions.androidx_room

    /**
     * https://developer.android.com/testing
     */
    const val espresso_core: String = "androidx.test.espresso:espresso-core:" +
            Versions.espresso_core

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_runner: String = "androidx.test:runner:" + Versions.androidx_test_runner

    /**
     * https://github.com/airbnb/epoxy
     */
    const val epoxy_processor: String = "com.airbnb.android:epoxy-processor:" +
            Versions.com_airbnb_android

    /**
     * https://github.com/airbnb/epoxy
     */
    const val epoxy: String = "com.airbnb.android:epoxy:" + Versions.com_airbnb_android

    /**
     * https://developer.android.com/studio
     */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    const val crashlytics: String = "com.crashlytics.sdk.android:crashlytics:" +
            Versions.crashlytics

    /**
     * https://github.com/VladimirWrites/Lemniscate
     */
    const val lemniscate: String = "com.github.VladimirWrites:Lemniscate:" + Versions.lemniscate

    /**
     * https://github.com/bumptech/glide
     */
    const val com_github_bumptech_glide_compiler: String = "com.github.bumptech.glide:compiler:" +
            Versions.com_github_bumptech_glide

    /**
     * https://github.com/bumptech/glide
     */
    const val glide: String = "com.github.bumptech.glide:glide:" +
            Versions.com_github_bumptech_glide

    /**
     * https://github.com/daniel-stoneuk/material-about-library
     */
    const val material_about_library: String = "com.github.daniel-stoneuk:material-about-library:" +
            Versions.material_about_library

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val material: String = "com.google.android.material:material:" + Versions.material

    const val firebase_core: String = "com.google.firebase:firebase-core:" + Versions.firebase_core

    /**
     * http://tools.android.com/
     */
    const val google_services: String = "com.google.gms:google-services:" + Versions.google_services

    /**
     * https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/
     */
    const val retrofit2_kotlin_coroutines_adapter: String =
            "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:" +
            Versions.retrofit2_kotlin_coroutines_adapter

    /**
     * https://github.com/JakeWharton/RxBinding/
     */
    const val rxbinding: String = "com.jakewharton.rxbinding2:rxbinding:" + Versions.rxbinding

    const val rxrelay: String = "com.jakewharton.rxrelay2:rxrelay:" + Versions.rxrelay

    const val com_pierfrancescosoffritti_androidyoutubeplayer_core: String =
            "com.pierfrancescosoffritti.androidyoutubeplayer:core:" +
            Versions.com_pierfrancescosoffritti_androidyoutubeplayer_core

    /**
     * https://github.com/square/moshi
     */
    const val moshi_adapters: String = "com.squareup.moshi:moshi-adapters:" +
            Versions.com_squareup_moshi

    /**
     * https://github.com/square/moshi
     */
    const val moshi_kotlin_codegen: String = "com.squareup.moshi:moshi-kotlin-codegen:" +
            Versions.com_squareup_moshi

    /**
     * https://github.com/square/moshi
     */
    const val moshi: String = "com.squareup.moshi:moshi:" + Versions.com_squareup_moshi

    /**
     * https://github.com/square/okhttp
     */
    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
            Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/okhttp
     */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/retrofit/
     */
    const val adapter_rxjava2: String = "com.squareup.retrofit2:adapter-rxjava2:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/
     */
    const val converter_moshi: String = "com.squareup.retrofit2:converter-moshi:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/
     */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" +
            Versions.com_squareup_retrofit2

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val io_fabric_tools_gradle: String = "io.fabric.tools:gradle:" +
            Versions.io_fabric_tools_gradle

    /**
     * https://github.com/ReactiveX/RxAndroid
     */
    const val rxandroid: String = "io.reactivex.rxjava2:rxandroid:" + Versions.rxandroid

    /**
     * https://github.com/ReactiveX/RxJava
     */
    const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

    /**
     * https://github.com/ReactiveX/RxKotlin
     */
    const val rxkotlin: String = "io.reactivex.rxjava2:rxkotlin:" + Versions.rxkotlin

    /**
     * http://junit.org
     */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
            Versions.kotlin_android_extensions_runtime

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.kotlin_android_extensions

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.kotlin_annotation_processing_gradle

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.kotlin_gradle_plugin

    /**
     * https://kotlinlang.org/
     */
    const val org_jetbrains_kotlin_kotlin_stdlib_jdk7: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
            Versions.org_jetbrains_kotlin_kotlin_stdlib_jdk7

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" + Versions.org_jetbrains_kotlinx

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
            Versions.org_jetbrains_kotlinx

    const val koin_android: String = "org.koin:koin-android:" + Versions.org_koin

    const val koin_androidx_scope: String = "org.koin:koin-androidx-scope:" + Versions.org_koin

    const val koin_androidx_viewmodel: String = "org.koin:koin-androidx-viewmodel:" +
            Versions.org_koin

    /**
     * https://github.com/mockito/mockito
     */
    const val mockito_core: String = "org.mockito:mockito-core:" + Versions.mockito_core
}
